server {
    listen 80;
    server_name somezing.me;

    location / {
        proxy_pass https://app:3000;  // Website on port 3000 via HTTPS
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name somezing.me;

    ssl_certificate /ssl/etc/live/somezing.me/fullchain.pem;
    ssl_certificate_key /ssl/etc/live/somezing.me/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass https://app:3001;  // API on port 3001 via HTTPS
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
