# HTTP server block for main web app (somezing.me)
server {
    listen 80;
    server_name somezing.me www.somezing.me;

    location / {
        proxy_pass https://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ /.well-known/acme-challenge {
        root /var/www/certbot;
    }
}

# HTTP server block for API (api.somezing.me)
server {
    listen 80;
    server_name api.somezing.me www.api.somezing.me;

    location / {
        proxy_pass https://app:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
