FROM node:20-alpine as build

WORKDIR /app

COPY . .

RUN npm ci
RUN npm run build

FROM node:20-alpine as production

COPY --from=build /app/dist /app/dist
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/number.js /app/number.js
COPY --from=build /app/node_modules /app/node_modules

EXPOSE 4173
EXPOSE 3001

CMD ["sh", "-c", "npm start & node number.js"]