FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY eslint.config.js eslint.config.js
COPY index.html index.html

RUN npm ci

COPY src src

RUN npm run build

FROM node:20-alpine AS production

COPY --from=build /app/dist /app/dist
COPY --from=build /app/package.json /app/package.json
COPY number.js number.js
COPY --from=build /app/node_modules /app/node_modules

EXPOSE 4173
EXPOSE 3001

CMD ["sh", "-c", "npm start & node number.js"]